# App Name & Web Server Configuration
spring.application.name=demo
server.port=8080

# Advanced File Size Processing Limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# In-Memory H2 Database Configuration for Free Cloud Hosting
spring.datasource.url=jdbc:h2:mem:dudedb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 web console viewer for backend debugging
spring.h2.console.enabled=true